### ISSUE TITLE
Release 10 RC 1

### ISSUE THREAD

**Issue by drozdziak1** [althea-mesh/althea-firmware#53]
# Additional TODO
* [x] - Wait until Adam's port toggling work makes it to althea-mesh/althea_rs
* [x] - Bump `althea-cron-jobs` in althea-mesh/althea-packages

**Comment by drozdziak1** [comment]
# Regressions
There's an ARM problem again
* [ ] - find a working toolchain

**Comment by asoltys** [comment]
I got the ports wrong for GL-B1300, fixed here: https://github.com/althea-mesh/althea-dash/commit/9c5e12a70a7a2ed7fa0d20b77122ee92f368cde3

**Comment by drozdziak1** [comment]
@asoltys Roger, commencing RC2
